# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wW3VPEzHsbjuGkOoOYFnZ6H0yJB8rzrg
"""

import os
os.makedirs("samples/original", exist_ok=True)
os.makedirs("samples/synthesized", exist_ok=True)

#!/usr/bin/env python3
"""
楽器音色 自動比較プログラム

【使い方】
  1. samples/original/   に元音源（GarageBandなど）を入れる
  2. samples/synthesized/ に自作合成音を入れる
     ※ original と synthesized で同じファイル名にすること
       各音程で比較を行うこと
  3. python3 auto_compare.py を実行する

【ファイル名の例】
  original/do.wav   ←→   synthesized/do.wav
  original/re.wav   ←→   synthesized/re.wav
  ...
"""

import sys, os, subprocess
from pathlib import Path

# ──────────────────────────────────────────────
# 必要パッケージの自動インストール
# ──────────────────────────────────────────────
def _install(pkg):
    for extra in [[], ['--break-system-packages'], ['--user']]:
        try:
            subprocess.check_call(
                [sys.executable, '-m', 'pip', 'install', pkg] + extra,
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            return True
        except subprocess.CalledProcessError:
            continue
    return False

def _ensure_packages():
    import importlib.util
    missing = [p for p in ['numpy', 'librosa']
               if importlib.util.find_spec(p) is None]
    if not missing:
        return
    print(f"[自動インストール] {', '.join(missing)} をインストール中...")
    for pkg in missing:
        print(f"  {pkg} ...", end=' ', flush=True)
        print("完了" if _install(pkg) else "失敗")
    print("再起動します...\n")
    os.execv(sys.executable, [sys.executable] + sys.argv)

_ensure_packages()

import numpy as np
import librosa

try:
    import tkinter as tk
except ModuleNotFoundError:
    print("tkinter が見つかりません。以下を実行してください:\n  brew install python-tk@3.12")
    sys.exit(1)

# ──────────────────────────────────────────────
# 定数
# ──────────────────────────────────────────────
TARGET     = 0.8
SR         = 22050
N_MFCC     = 13
N_FFT      = 2048
HOP_LEN    = 512
N_MELS     = 40
EXTS       = {'.wav', '.mp3', '.flac', '.aif', '.aiff', '.ogg'}

SCRIPT_DIR = Path("/content").parent
ORIG_DIR   = SCRIPT_DIR / 'samples' / 'original'
SYNTH_DIR  = SCRIPT_DIR / 'samples' / 'synthesized'

# ──────────────────────────────────────────────
# 音声処理
# ──────────────────────────────────────────────
def extract(path: Path) -> np.ndarray:
    y, _ = librosa.load(str(path), sr=SR, mono=True)
    y, _ = librosa.effects.trim(y, top_db=20)
    y    = np.append(y[0], y[1:] - 0.97 * y[:-1])
    m    = librosa.feature.mfcc(
               y=y, sr=SR, n_mfcc=N_MFCC, n_fft=N_FFT,
               hop_length=HOP_LEN, n_mels=N_MELS)
    sc   = librosa.feature.spectral_contrast(
               y=y, sr=SR, n_fft=N_FFT, hop_length=HOP_LEN)
    return np.concatenate([np.mean(m, axis=1), np.std(m, axis=1),
                           np.mean(sc, axis=1)])

def cosine_sim(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))

def find_file(folder: Path, stem: str) -> Path | None:
    for ext in EXTS:
        p = folder / f'{stem}{ext}'
        if p.exists():
            return p
    return None

# ──────────────────────────────────────────────
# 比較ロジック
# ──────────────────────────────────────────────
def run_comparison() -> list[dict]:
    """
    original/ 内の音声ファイルを走査し、synthesized/ と比較する。
    returns: [ { name, orig, synth, score, status } ]
      status: 'ok' | 'no_synth' | 'no_orig' | 'error'
    """
    rows = []

    if not ORIG_DIR.exists():
        return rows

    orig_files = sorted(
        f for f in ORIG_DIR.iterdir() if f.suffix.lower() in EXTS
    )

    for orig in orig_files:
        synth = find_file(SYNTH_DIR, orig.stem)
        if synth is None:
            rows.append({'name': orig.name, 'orig': orig,
                         'synth': None, 'score': None, 'status': 'no_synth'})
            continue
        try:
            score = cosine_sim(extract(orig), extract(synth))
            rows.append({'name': orig.name, 'orig': orig, 'synth': synth,
                         'score': round(score, 4), 'status': 'ok'})
        except Exception as e:
            rows.append({'name': orig.name, 'orig': orig, 'synth': synth,
                         'score': None, 'status': 'error', 'error': str(e)})
    return rows

# ──────────────────────────────────────────────
# GUI
# ──────────────────────────────────────────────
COL_HEAD  = ('#343a40', '#ffffff')
COL_PASS  = ('#d4edda', '#155724')
COL_FAIL  = ('#f8d7da', '#721c24')
COL_WARN  = ('#fff3cd', '#856404')
COL_EVEN  = ('#f8f9fa', '#333333')
COL_ODD   = ('#ffffff', '#333333')

class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title('楽器音色 自動比較')
        self.resizable(True, True)
        self._build()
        self.after(100, self._run)

    def _build(self):
        tk.Label(self, text='楽器音色 自動比較',
                 font=('', 15, 'bold'), pady=10).pack()

        self.status_var = tk.StringVar(value='比較中...')
        tk.Label(self, textvariable=self.status_var,
                 font=('', 10), fg='#555').pack()

        # テーブル
        self.tbl = tk.Frame(self, bd=1, relief='sunken')
        self.tbl.pack(padx=24, pady=12, fill='both', expand=True)

        # ボタン
        bf = tk.Frame(self)
        bf.pack(pady=10)
        tk.Button(bf, text='再比較', font=('', 11),
                  bg='#007bff', fg='white', padx=20, pady=6,
                  activebackground='#0056b3',
                  command=self._run).pack(side='left', padx=6)
        tk.Button(bf, text='original を開く', font=('', 11),
                  padx=12, pady=6,
                  command=lambda: os.system(f'open "{ORIG_DIR}"')
                  ).pack(side='left', padx=6)
        tk.Button(bf, text='synthesized を開く', font=('', 11),
                  padx=12, pady=6,
                  command=lambda: os.system(f'open "{SYNTH_DIR}"')
                  ).pack(side='left', padx=6)

    # ── セル描画ヘルパー ──
    def _cell(self, text, bg, fg, row, col, bold=False, anchor='center', width=None):
        kw = dict(text=text, bg=bg, fg=fg,
                  font=('', 10, 'bold') if bold else ('', 10),
                  relief='flat', padx=10, pady=6,
                  anchor=anchor)
        if width:
            kw['width'] = width
        lbl = tk.Label(self.tbl, **kw)
        lbl.grid(row=row, column=col, sticky='nsew', padx=1, pady=1)

    def _draw(self, rows: list[dict]):
        for w in self.tbl.winfo_children():
            w.destroy()

        # ヘッダー
        for col, (text, w) in enumerate([('ファイル名', 28),
                                          ('類似度', 10),
                                          ('判定', 8),
                                          ('状態', 14)]):
            self._cell(text, *COL_HEAD, row=0, col=col, bold=True, width=w)

        if not rows:
            lbl = tk.Label(self.tbl,
                text='original フォルダに音声ファイルが見つかりません。\n'
                     'samples/original/ に元音源（.wav等）を入れてください。',
                fg='gray', font=('', 11), pady=30, bg='white')
            lbl.grid(row=1, column=0, columnspan=4, sticky='nsew')
            return

        for r, row in enumerate(rows, 1):
            bg, fg = (COL_EVEN if r % 2 == 0 else COL_ODD)
            self._cell(row['name'], bg, fg, row=r, col=0, anchor='w')

            s = row['score']
            st = row['status']

            if st == 'ok':
                score_txt = f'{s:.4f}'
                judge_txt = '✓ 達成' if s >= TARGET else '✗ 未達成'
                c = COL_PASS if s >= TARGET else COL_FAIL
                self._cell(score_txt, *c, row=r, col=1)
                self._cell(judge_txt, *c, row=r, col=2, bold=True)
                self._cell('', bg, fg, row=r, col=3)
            elif st == 'no_synth':
                self._cell('---',  bg, fg, row=r, col=1)
                self._cell('---',  bg, fg, row=r, col=2)
                self._cell('synthesized に対応ファイルなし', *COL_WARN, row=r, col=3)
            else:
                self._cell('エラー', bg, fg, row=r, col=1)
                self._cell('---',   bg, fg, row=r, col=2)
                self._cell(row.get('error', '')[:40], *COL_WARN, row=r, col=3)

        # グリッドのカラム幅を均等に
        for col in range(4):
            self.tbl.columnconfigure(col, weight=1)

    def _run(self):
        self.status_var.set('比較中...')
        self.update()

        rows = run_comparison()
        self._draw(rows)

        ok     = [r for r in rows if r['status'] == 'ok']
        passed = [r for r in ok   if r['score'] >= TARGET]

        if ok:
            avg = np.mean([r['score'] for r in ok])
            self.status_var.set(
                f'比較: {len(ok)}件  ✓達成: {len(passed)}件  '
                f'✗未達成: {len(ok)-len(passed)}件  ｜  平均類似度: {avg:.4f}')
        elif rows:
            self.status_var.set('synthesized に対応ファイルがありません。')
        else:
            self.status_var.set(
                'ファイルが見つかりません — '
                'samples/original/ に音声ファイルを入れてください。')

if __name__ == '__main__':
    App().mainloop()

import sys, os, subprocess
from pathlib import Path

def _install(pkg):
    for extra in [[], ['--break-system-packages'], ['--user']]:
        try:
            subprocess.check_call(
                [sys.executable, '-m', 'pip', 'install', pkg] + extra,
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            return True
        except subprocess.CalledProcessError:
            continue
    return False

def _ensure_packages():
    import importlib.util
    missing = [p for p in ['numpy', 'librosa']
               if importlib.util.find_spec(p) is None]
    if not missing:
        return
    print(f"[自動インストール] {', '.join(missing)} をインストール中...")
    for pkg in missing:
        print(f"  {pkg} ...", end=' ', flush=True)
        print("完了" if _install(pkg) else "失敗")

_ensure_packages()

import numpy as np
import librosa

# ──────────────────────────────────────────────
# 定数
# ──────────────────────────────────────────────
TARGET  = 0.8
SR      = 22050
N_MFCC  = 13
N_FFT   = 2048
HOP_LEN = 512
N_MELS  = 40
EXTS    = {'.wav', '.mp3', '.flac', '.aif', '.aiff', '.ogg'}

ORIG_DIR  = Path("/content/samples/original")
SYNTH_DIR = Path("/content/samples/synthesized")

# ──────────────────────────────────────────────
# 音声処理
# ──────────────────────────────────────────────
def extract(path: Path) -> np.ndarray:
    y, _ = librosa.load(str(path), sr=SR, mono=True)
    y, _ = librosa.effects.trim(y, top_db=20)
    y    = np.append(y[0], y[1:] - 0.97 * y[:-1])
    m    = librosa.feature.mfcc(
               y=y, sr=SR, n_mfcc=N_MFCC, n_fft=N_FFT,
               hop_length=HOP_LEN, n_mels=N_MELS)
    sc   = librosa.feature.spectral_contrast(
               y=y, sr=SR, n_fft=N_FFT, hop_length=HOP_LEN)
    return np.concatenate([np.mean(m, axis=1), np.std(m, axis=1),
                           np.mean(sc, axis=1)])

def cosine_sim(a: np.ndarray, b: np.ndarray) -> float:
    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))

def find_file(folder: Path, stem: str) -> Path | None:
    for ext in EXTS:
        p = folder / f'{stem}{ext}'
        if p.exists():
            return p
    return None

# ──────────────────────────────────────────────
# 比較ロジック
# ──────────────────────────────────────────────
def run_comparison():
    rows = []
    if not ORIG_DIR.exists():
        print("❌ samples/original/ フォルダが見つかりません")
        return rows

    orig_files = sorted(
        f for f in ORIG_DIR.iterdir() if f.suffix.lower() in EXTS
    )

    for orig in orig_files:
        synth = find_file(SYNTH_DIR, orig.stem)
        if synth is None:
            rows.append({'name': orig.name, 'score': None, 'status': 'no_synth'})
            continue
        try:
            score = cosine_sim(extract(orig), extract(synth))
            rows.append({'name': orig.name, 'score': round(score, 4), 'status': 'ok'})
        except Exception as e:
            rows.append({'name': orig.name, 'score': None, 'status': 'error', 'error': str(e)})
    return rows

# ──────────────────────────────────────────────
# 結果表示
# ──────────────────────────────────────────────
def show_results(rows):
    print("=" * 50)
    print("　楽器音色 自動比較 結果")
    print("=" * 50)

    if not rows:
        print("ファイルが見つかりませんでした。")
        return

    for row in rows:
        name = row['name']
        st   = row['status']
        if st == 'ok':
            s = row['score']
            judge = "✓ 達成" if s >= TARGET else "✗ 未達成"
            print(f"{name:<20} 類似度: {s:.4f}  {judge}")
        elif st == 'no_synth':
            print(f"{name:<20} ⚠️  synthesized に対応ファイルなし")
        else:
            print(f"{name:<20} ❌ エラー: {row.get('error', '')}")

    ok     = [r for r in rows if r['status'] == 'ok']
    passed = [r for r in ok   if r['score'] >= TARGET]

    if ok:
        avg = np.mean([r['score'] for r in ok])
        print("-" * 50)
        print(f"比較: {len(ok)}件　✓達成: {len(passed)}件　✗未達成: {len(ok)-len(passed)}件")
        print(f"平均類似度: {avg:.4f}")
    print("=" * 50)

rows = run_comparison()
show_results(rows)